# Generated by Django 6.0.1 on 2026-02-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_effective_date',
            field=models.DateTimeField(blank=True, help_text='When the pending plan will become active', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, help_text='Plan scheduled to activate at end of current period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='subscriptions.plan'),
        ),
    ]
