# Generated by Django 6.0.1 on 2026-02-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0011_faqdesign_layout_model'),
        ('subscriptions', '0002_subscription_pending_effective_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='faq_app.shop'),
        ),
    ]
