# Generated by Django 6.0.1 on 2026-01-17 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('shop_name', models.CharField(max_length=255)),
                ('shopify_access_token_encrypted', models.TextField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('shopify_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('handle', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('has_faq', models.BooleanField(db_index=True, default=False)),
                ('should_regenerate', models.BooleanField(default=True)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='faq_app.shop')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_store_url', models.CharField(max_length=255)),
                ('shopify_access_token_encrypted', models.TextField()),
                ('shopify_api_version', models.CharField(blank=True, max_length=50, null=True)),
                ('anthropic_api_key_encrypted', models.TextField(blank=True, null=True)),
                ('has_custom_anthropic_key', models.BooleanField(default=False)),
                ('dataseo_api_key_encrypted', models.TextField(blank=True, null=True)),
                ('has_custom_dataseo_key', models.BooleanField(default=False)),
                ('use_default_keys', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_configuration', to='faq_app.shop')),
            ],
            options={
                'db_table': 'api_configurations',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('operation', models.CharField(db_index=True, max_length=100)),
                ('product_title', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='faq_app.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='faq_app.shop')),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='WebhookRegistration',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('total_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_registrations', to='faq_app.shop')),
            ],
            options={
                'db_table': 'webhook_registrations',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_answers', models.JSONField()),
                ('html_content', models.TextField()),
                ('num_questions', models.IntegerField()),
                ('generated_with_claude', models.BooleanField(default=True)),
                ('generated_with_dataseo', models.BooleanField(default=True)),
                ('generation_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('was_manual_edit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faq_app.product')),
            ],
            options={
                'db_table': 'faqs',
                'indexes': [models.Index(fields=['product', 'is_active'], name='faqs_product_713867_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'has_faq', 'should_regenerate'], name='products_shop_id_7476bc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'updated_at'], name='products_shop_id_833ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['shop', 'level', 'timestamp'], name='activity_lo_shop_id_5a7927_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['shop', 'operation', 'timestamp'], name='activity_lo_shop_id_11a3e0_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['shop', 'timestamp'], name='activity_lo_shop_id_739a55_idx'),
        ),
    ]
