# Generated by Django 6.0.1 on 2026-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0004_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfiguration',
            name='custom_prompt',
            field=models.TextField(blank=True, help_text='Custom system prompt for FAQ generation', null=True),
        ),
        migrations.AddField(
            model_name='apiconfiguration',
            name='has_custom_openai_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiconfiguration',
            name='openai_api_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
