# Generated by Django 6.0.1 on 2026-01-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0005_apiconfiguration_custom_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfiguration',
            name='claude_model',
            field=models.CharField(choices=[('claude-3-haiku-20240307', 'Claude 3 Haiku (Plus rapide/Économique)'), ('claude-3-sonnet-20240229', 'Claude 3 Sonnet (Équilibré)'), ('claude-3-5-sonnet-20240620', 'Claude 3.5 Sonnet (Recommandé/Intelligent)'), ('claude-3-opus-20240229', 'Claude 3 Opus (Puissance maximale)')], default='claude-3-haiku-20240307', max_length=100),
        ),
    ]
