# Generated by Django 6.0.1 on 2026-01-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0006_apiconfiguration_claude_model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webhookregistration',
            table=None,
        ),
        migrations.CreateModel(
            name='FAQDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_color', models.CharField(default='#1e293b', max_length=20)),
                ('answer_color', models.CharField(default='#475569', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('border_color', models.CharField(default='#e2e8f0', max_length=20)),
                ('font_size', models.IntegerField(default=16, help_text='Font size in pixels')),
                ('border_radius', models.IntegerField(default=12, help_text='Border radius in pixels')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS to override styles', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq_design', to='faq_app.shop')),
            ],
            options={
                'db_table': 'faq_designs',
            },
        ),
    ]
