# Generated by Django 6.0.1 on 2026-01-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0007_alter_webhookregistration_table_faqdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqdesign',
            name='title',
            field=models.CharField(default='Questions Fréquentes', help_text='Title of the FAQ section', max_length=200),
        ),
    ]
