# Generated by Django 6.0.1 on 2026-01-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0008_faqdesign_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqdesign',
            name='answer_icon_bg',
            field=models.CharField(default='#f0fdf4', help_text='Background color for R icon', max_length=20),
        ),
        migrations.AddField(
            model_name='faqdesign',
            name='answer_icon_color',
            field=models.CharField(default='#15803d', help_text='Text color for R icon', max_length=20),
        ),
        migrations.AddField(
            model_name='faqdesign',
            name='answer_icon_text',
            field=models.CharField(default='R', help_text='Text/emoji for answer icon', max_length=10),
        ),
        migrations.AddField(
            model_name='faqdesign',
            name='font_family',
            field=models.CharField(default='system-ui', help_text='Font family', max_length=100),
        ),
        migrations.AddField(
            model_name='faqdesign',
            name='question_icon_bg',
            field=models.CharField(default='#e0f2fe', help_text='Background color for Q icon', max_length=20),
        ),
        migrations.AddField(
            model_name='faqdesign',
            name='question_icon_color',
            field=models.CharField(default='#0369a1', help_text='Text color for Q icon', max_length=20),
        ),
        migrations.AddField(
            model_name='faqdesign',
            name='question_icon_text',
            field=models.CharField(default='Q', help_text='Text/emoji for question icon', max_length=10),
        ),
    ]
