# Generated by Django 6.0.1 on 2026-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0009_faqdesign_answer_icon_bg_faqdesign_answer_icon_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='questions_answers_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='questions_answers_es',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
