# Generated by Django 6.0.1 on 2026-01-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0010_faq_questions_answers_en_faq_questions_answers_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqdesign',
            name='layout_model',
            field=models.CharField(choices=[('classic', 'Accordéon Classique'), ('modern', 'Accordéon Moderne'), ('minimal', 'Liste Minimaliste'), ('cards', 'Grille de Cartes')], default='classic', max_length=50),
        ),
    ]
