# Generated by Django 6.0.1 on 2026-02-03 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0011_faqdesign_layout_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkGenerationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('total_products', models.IntegerField(default=0)),
                ('processed_products', models.IntegerField(default=0)),
                ('mode', models.CharField(choices=[('ALL', 'For all products'), ('MISSING_ONLY', 'Only products without FAQs')], default='MISSING_ONLY', max_length=20)),
                ('current_product_title', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_job', to='faq_app.shop')),
            ],
            options={
                'db_table': 'bulk_generation_jobs',
            },
        ),
    ]
