# Generated by Django 6.0.1 on 2026-03-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0012_bulkgenerationjob'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE faq_designs CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE faq_designs CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE faq_designs MODIFY question_icon_text VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            reverse_sql="ALTER TABLE faq_designs MODIFY question_icon_text VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE faq_designs MODIFY answer_icon_text VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            reverse_sql="ALTER TABLE faq_designs MODIFY answer_icon_text VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;"
        ),
    ]
